apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: extractor-production-ingress
  annotations:
    kubernetes.io/ingressClassName: "nginx"
    kubernetes.io/ingress.global-static-ip-name: "extractor-production-ip"
    networking.gke.io/managed-certificates: "extractor-production-managed-certificate"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: extractor-production-managed-certificate
spec:
  domains:
    - production.sushi.com