[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.extractor"
watchPatterns = ["apis/extractor/**", "packages/**", "!/*.md", "bun.lockb", "package.json", "Dockerfile.extractor", "extractor.railway.toml"]

[deploy]
numReplicas = 1
healthcheckPath = "/health"
sleepApplication = false
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 15

[environments.pr.deploy]
sleepApplication = true

[environments.production.deploy]
sleepApplication = false
numReplicas = 2