sources:
  - name: Steer
    handler:
      graphql:
        endpoint: https://{context.url:api.thegraph.com/subgraphs/name/steerprotocol/steer-protocol-polygon}
        retry: 3
    transforms:
      - prefix:
          value: Steer_
          includeRootOperations: true
          includeTypes: true

transforms:
  - autoPagination:
      validateSchema: false
  - autoTypeMerging: true
  - addSourceName: true

documents:
  - ./query.graphql

codegen:
  contextType: 'MeshContext & { chainId: string; subgraphName: string; subgraphHost: string }'

