{{- $chainIds := .Values.chainIds }}
{{- range $index, $value := $chainIds }}
apiVersion: v1
kind: Service
metadata:
  name: extractor-{{ $value }}-service
spec:
  selector:
    app: extractor-{{ $value }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
{{- end }}