{{- $chainIds := .Values.chainIds }}
{{- range $index, $value := $chainIds }}
apiVersion: v1
kind: Service
metadata:
  name: router-{{ $value }}
  labels:
    app: router-{{ $value }}
spec:
  selector:
    app: router-{{ $value }}
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
{{- end }}