steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg'
      - 'SCRIPT_PATH=./packages/extractor'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:latest'
      - '-f'
      - './packages/extractor/Dockerfile'
      - .
    dir: /workspace
    id: Build Docker Image
  - name: gcr.io/cloud-builders/docker
    env:
      - '_SCRIPT_PATH=${_SCRIPT_PATH}'
      - '_TURBO_TEAM=${_TURBO_TEAM}'
      - '_TURBO_TOKEN=${_TURBO_TOKEN}'
    args:
      - build
      - '--build-arg'
      - 'SCRIPT_PATH=${_SCRIPT_PATH}'
      - '--build-arg'
      - 'TURBO_TEAM=${_TURBO_TEAM}'
      - '--build-arg'
      - 'TURBO_TOKEN=${_TURBO_TOKEN}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:latest'
      - .
    dir: /workspace
    id: Build Docker Image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:latest'
    id: Push Docker Image
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    env:
      - 'DRPC_ID=${_DRPC_ID}'
      - 'ALCHEMY_ID=${_ALCHEMY_ID}'
      - 'SENTRY_DSN=${_SENTRY_DSN}'
    args:
      - run
      - deploy
      - $TRIGGER_NAME
      - '--image'
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:latest'
      - '--region'
      - us-central1
      - '--set-env-vars=ALCHEMY_ID=$_ALCHEMY_ID'
      - '--set-env-vars=DRPC_ID=$_DRPC_ID'
      - '--set-env-vars=SENTRY_DSN=$_SENTRY_DSN'
    id: Update Cloud Run Service
    entrypoint: gcloud
timeout: 3600s
images:
  - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:latest'
options:
  machineType: E2_HIGHCPU_8
