name: Sushi - apps / swap / e2e

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/apps-swap-e2e.yml"
      - "apps/_root/**"
      - "config/nextjs/**"
      - "config/react-query/**"
      - "config/router/**"
      - "config/tailwindcss/**"
      - "config/typescript/**"
      - "config/viem/**"
      - "config/wagmi/**"
      - "packages/**"

defaults:
  run:
    # change this if your nextjs app does not live at the root of the repo
    working-directory: ./apps/_root

# https://playwright.dev/docs/ci#sharding
env:
  CI: true
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  NODE_OPTIONS: --max-old-space-size=8192
  NEXT_TELEMETRY_DISABLED: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  e2e:
      name: Swap E2E Tests
      timeout-minutes: 30
      runs-on: ubuntu-latest
      # env:
      strategy:
        matrix:
          chain-id: [1, 137, 42161]
          node-version: [18]
          pnpm-version: [7.9.5]
          include:
            - playwright-url: http://localhost:3000/swap
            - chain-id: 1
              block-number: 17284226
            - chain-id: 137
              block-number: 42259027
            - chain-id: 42161
              block-number: 91850294
      steps:
        - name: Check out
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
            submodules: true

        - uses: pnpm/action-setup@v2
          with:
            version: ${{ matrix.pnpm-version }}

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'

        - name: Cache pnpm
          uses: actions/cache@v3
          with:
            path: ~/.pnpm-store
            key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
            restore-keys: pnpm-

        - name: Install dependencies
          run: pnpm install
          working-directory: .

        - name: Install playwright
          run: pnpm exec playwright install --with-deps chromium

        - name: Install Foundry
          uses: foundry-rs/foundry-toolchain@v1

        # /home/runner/work/sushiswap/sushiswap

        - name: Test swap app
          run: pnpm test-root-app
          env:
            ACADEMY_URL: 'https://academy.sushi.com'
            ANALYTICS_URL: 'https://analytics.sushi.com'
            BLOG_URL: 'https://blog.sushi.com'
            EARN_URL: https://earn.sushi.com'
            FURO_URL: 'https://furo.sushi.com'
            ALCHEMY_ID: ${{ secrets.ALCHEMY_ID }}
            NEXT_PUBLIC_ALCHEMY_ID: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}
            NEXT_PUBLIC_TEST: true
            CHAIN_ID: ${{ matrix.chain-id }}
            PLAYWRIGHT_URL: ${{ matrix.playwright-url }}
            ANVIL_BLOCK_NUMBER: ${{ matrix.block-number }}
          working-directory: .

        - name: Upload test results
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: playwright-report
            path: ./apps/_root/test-results/