# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: extractor
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: extractor
      context: ../../
      docker:
        dockerfile: Dockerfile
        # buildArgs:
        #   TURBO_TEAM: "teamsushi"
        #   TURBO_TOKEN:{{ .TURBO_TOKEN }}
deploy:
  helm:
    releases:
      - name: extractors
        chartPath: k8s/chart
profiles:
- name: local
- name: staging
  build:
    googleCloudBuild:
      projectId: "extractor-410208"
  manifests:
    rawYaml:
      - k8s/ingress-staging.yaml
- name: production
  build:
    googleCloudBuild:
      projectId: "extractor-410208"
  manifests:
    rawYaml:
      - k8s/ingress-production.yaml